### ISSUE TITLE
Test low-resolution wild images

### ISSUE THREAD

**Issue by CodingMice** [JizhiziLi/GFM#1] opened 2020-11-05 03:47 UTC
I test the given pretrained model using the wild images from internet, but get bad results. masks are almost zero. Is something wrong?

**Comment by JizhiziLi** [comment] 2020-11-05 04:06
Hi there,

Please note the pretrained model is suitable for high-resolution animal images with the clear animal foregrounds (some good website candidates e.g. https://unsplash.com/, https://www.pexels.com/, https://burst.shopify.com/, etc), please follow the guidance in the section "Inference code" and try test on samples images we provided first to make sure you have used the correct pipeline. If you still encounter problems, feel free to email your sample images and the issue you have encountered to jili8515@uni.sydney.edu.au for further discussion. Thanks!

**Comment by CodingMice** [comment] 2020-11-05 05:30
@JizhiziLi  Thanks for your answer.  The images I used to test is low-resolution animal images. After I use the high-resolution images as you said, I could get good results. Nice works!

**Comment by JizhiziLi** [comment] 2020-11-05 05:59
@CodingMice No worries! I am going to close this issue since the problem is resolved. Let me know if you have further questions. :)

**Closed as completed by JizhiziLi** 2020-11-05 05:59 UTC
